# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  my.listener:
     class: AppBundle\EventListener\CheckMeasure
     arguments: [ '@validator']
     tags:
        - { name: doctrine.event_listener, event: prePersist }

  my.validator:
     class: AppBundle\Validator\Constraints\LessThanParameterValidator
     arguments: ['%queuetime%' ]
     tags:
        - { name: validator.constraint_validator }
